# Site settings
title: Kenneth Calamay => Ruby on Rails |> Elixir & Phoenix
email: web@kennethcalamay.com
description: > # this means to ignore newlines until "baseurl:"
  A web developer you can hire for your web development needs. Come, taste and see the Kenneth Calamay difference.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kennethcalamay.github.io" # the base hostname & protocol for your site
twitter_username: kltcal
github_username:  kennethcalamay

# Build settings
markdown: kramdown
